[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
memory_limit = 33554432  # 32MB
gas_limit = 9223372036854775807  # max u64
viaIR = true

remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts'
]

[rpc_endpoints]
hyperevm = "https://rpc.hyperliquid.xyz/evm"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
