[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
memory_limit = 33554432  # 32MB
gas_limit = 9223372036854775807  # max u64
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
viaIR = true 
rpc_endpoints = { hyperevm = "https://rpc.hyperliquid.xyz/evm" }
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts',
    'openzeppelin-foundry-upgrades/=lib/openzeppelin-foundry-upgrades/src'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
